### ISSUE TITLE
Diagramas

### ISSUE THREAD

**Issue by juliobacoli** [LucaFarabello/Projeto-APDII#1]
- Diagrama de Componentes
- Diagrama de Pacotes (é composto por pacotes)
- Diagrama de Modelo (é composto por camadas e pacotes)
- Diagrama de Deployment (é composto por: nós, artefatos, elementos de comunicação) será usado para modelar a visão infraestrutura e a  tecnologia
[DSII - Componentes, Pacotes e Deployment.pptx](https://github.com/LucaFarabello/Projeto-APDII/files/3567404/DSII.-.Componentes.Pacotes.e.Deployment.pptx)

**Comment by juliobacoli** [comment]
Todos esses diagramas precisam estar na wiki nas suas devidas visões.

**Visão Computação:** Diagrama de pacotes
**Visão Infraestrutura e tecnologia:** Diagrama de deployment

**Comment by marianaaraujogAG** [comment]
Diagrama de Modelo de Dominio

![a4ba2515-e995-420d-9f22-0730bfa71086](https://user-images.githubusercontent.com/50681422/65002146-cc0d6700-d8c8-11e9-8821-409394ee0f50.jpg)

**Comment by juliobacoli** [comment]
Diagrama de Componentes

![diagrama de componente](https://user-images.githubusercontent.com/36744554/65003139-77201f80-d8cd-11e9-8a3d-79b74d6f9847.jpg)

**Comment by marianaaraujogAG** [comment]
Diagrama de Pacotes
![Diagrama de pacotes](https://user-images.githubusercontent.com/50681422/65003189-bfd7d880-d8cd-11e9-8261-5ff54884416b.jpg)
