### ISSUE TITLE
Concluir Visão - Empresa, Informação, Computação, Infraestrutura e Tecnologia

### ISSUE THREAD

**Issue by juliobacoli** [LucaFarabello/Projeto-APDII#3]
[Aula01Projeto -Roteiro_Laboratorio_Engenharia_Produto.pptx](https://github.com/LucaFarabello/Projeto-APDII/files/3567402/Aula01Projeto.-Roteiro_Laboratorio_Engenharia_Produto.pptx)
Precisamos concluir essas visões.

**Comment by marianaaraujogAG** [comment]
Visão Empresa - https://github.com/LucaFarabello/Projeto-APDII/wiki/VIS%C3%83O-EMPRESA

Visão Informação - https://github.com/LucaFarabello/Projeto-APDII/wiki/VIS%C3%83O-INFORMA%C3%87%C3%83O

Visão Computacional - https://github.com/LucaFarabello/Projeto-APDII/wiki/VIS%C3%83O-COMPUTA%C3%87%C3%83O

Visão Infraestrutura e Tecnologia - https://github.com/LucaFarabello/Projeto-APDII/wiki/VIS%C3%83O-INFRAESTRUTURA-E-TECNOLOGIA

**Comment by marianaaraujogAG** [comment]
Visão computação - Arquitetura de 3 camadas para cada serviço
Visão infraestrutura - Modelo de infraestrutura de rede e servidores

**Comment by juliobacoli** [comment]
Finalizado
